[project]
name = "langchain_cours_mlops"
version = "0.2.0"
description = "Updated LangChain Course"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "langchain==1.2.12",
    "langchain-core==1.2.20",
    "langchain-community==0.4.1",
    "langgraph>=1.1.5,<1.2",
    "langsmith==0.7.20",
    "langchain-groq==1.1.2",
    "langchain-openai==1.1.11",
    "pydantic==2.11.7",
    "python-dotenv==1.1.1",
]
