from langchain_core.messages import HumanMessage, SystemMessage
from src.core.llm import llm
from src.core.tools import word_count, char_count

print("\n=== Chapter 1: Fundamental Components ===\n")

print("--- INVOKE ---")
response = llm.invoke([
    SystemMessage(content="You are an MLOps expert assistant."),
    HumanMessage(content="Explain how LangChain helps structure an LLM application.")
])
print(response.content)

print("\n--- RESPONSE ANALYSIS ---")
print("Number of words      :", word_count.invoke(response.content))
print("Number of characters :", char_count.invoke(response.content))

print("\n--- BATCH ---")
batch_inputs = [
    [
        SystemMessage(content="You are a synonym assistant."),
        HumanMessage(content="Give a synonym for fast.")
    ],
    [
        SystemMessage(content="You are a scientific assistant."),
        HumanMessage(content="Explain what an artificial neuron is.")
    ]
]

batch_outputs = llm.batch(batch_inputs)
for i, r in enumerate(batch_outputs, 1):
    print(f"\nResponse {i}:", r.content)

print("\n--- STREAMING ---")
stream_text = ""
for chunk in llm.stream("Write a short paragraph on the uses of AI agents."):
    print(chunk.content, end="", flush=True)
    stream_text += chunk.content

print("\n\nAnalysis of text generated by streaming:")
print("Number of words      :", word_count.invoke(stream_text))
print("Number of characters :", char_count.invoke(stream_text))